-- Script para insertar todas las materias primas
-- Ejecutar este script en Supabase SQL Editor o mediante migración

INSERT INTO raw_materials (code, name, unit) VALUES
('RM-001', '15-0-9', 'unidad'),
('RM-002', 'Acido acetico', 'unidad'),
('RM-003', 'Acido Ascorbico', 'unidad'),
('RM-004', 'Acido bórico', 'unidad'),
('RM-005', 'Acido Citrico anhidro Kg.', 'Kg'),
('RM-006', 'Acido Clorhídrico', 'unidad'),
('RM-007', 'Ácido Folico', 'unidad'),
('RM-008', 'Acido Fosforico 85%', 'unidad'),
('RM-009', 'Acido Fosforoso 98,5%', 'unidad'),
('RM-010', 'Acido Fulvico', 'unidad'),
('RM-011', 'Acido Glutamico', 'unidad'),
('RM-012', 'Acido Humico', 'unidad'),
('RM-013', 'Acido L-lactico', 'unidad'),
('RM-014', 'Acido Nitrico', 'unidad'),
('RM-015', 'Acido Salicílico', 'unidad'),
('RM-016', 'Acido Sulfurico', 'unidad'),
('RM-017', 'Agua', 'unidad'),
('RM-018', 'Alga maxicrop', 'unidad'),
('RM-019', 'Alga seca', 'unidad'),
('RM-020', 'Amoniaco', 'unidad'),
('RM-021', 'ANA', 'unidad'),
('RM-022', 'Azucar', 'unidad'),
('RM-023', 'Azufre', 'unidad'),
('RM-024', 'Base Alga', 'unidad'),
('RM-025', 'Benzoato de sodio', 'unidad'),
('RM-026', 'Borax', 'unidad'),
('RM-027', 'Boronatrocalcita', 'unidad'),
('RM-028', 'Borregro', 'unidad'),
('RM-029', 'Borresol', 'unidad'),
('RM-030', 'Caolin', 'unidad'),
('RM-031', 'Cloruro de Amonio', 'unidad'),
('RM-032', 'Cloruro de Calcio 94%', 'unidad'),
('RM-033', 'Cloruro de Magnesio', 'unidad'),
('RM-034', 'Cloruro de Potasio', 'unidad'),
('RM-035', 'Cloruro de Zinc', 'unidad'),
('RM-036', 'Colorante Amarillo', 'unidad'),
('RM-037', 'Colorante verde', 'unidad'),
('RM-038', 'Disal (Naftalen sulfonato)', 'unidad'),
('RM-039', 'EDTA', 'unidad'),
('RM-040', 'Extracto de Algas', 'unidad'),
('RM-041', 'Extracto de levadura', 'unidad'),
('RM-042', 'Formalina', 'unidad'),
('RM-043', 'Fosfato Monoamonico', 'unidad'),
('RM-044', 'Fosfato Monopotasico', 'unidad'),
('RM-045', 'Gluconato de sodio', 'unidad'),
('RM-046', 'Goma Xantato', 'unidad'),
('RM-047', 'Hidroxido de Amonio', 'unidad'),
('RM-048', 'Hidroxido de Calcio', 'unidad'),
('RM-049', 'Hidroxido de Potasio Escama', 'unidad'),
('RM-050', 'Hidroxido de Potasio Liquida', 'unidad'),
('RM-051', 'Hidroxido de Sodio', 'unidad'),
('RM-052', 'Lignosulfonato', 'unidad'),
('RM-053', 'Lisapol', 'unidad'),
('RM-054', 'Manitol', 'unidad'),
('RM-055', 'Molibdato de Amonio', 'unidad'),
('RM-056', 'Molibdato de Sodio', 'unidad'),
('RM-057', 'Monoetanolamina', 'unidad'),
('RM-058', 'Nitrato de Amonio', 'unidad'),
('RM-059', 'Nitrato de Amonio Agricola', 'unidad'),
('RM-060', 'Nitrato de Calcio', 'unidad'),
('RM-061', 'Nitrato de magnesio', 'unidad'),
('RM-062', 'Nitrato de Potasio', 'unidad'),
('RM-063', 'Nitrato de Sodio', 'unidad'),
('RM-064', 'Nitrato de Zinc', 'unidad'),
('RM-065', 'Oxido de Magnesio', 'unidad'),
('RM-066', 'Oxido de Zinc', 'unidad'),
('RM-067', 'Poliol', 'unidad'),
('RM-068', 'Propilenglicol', 'unidad'),
('RM-069', 'Rhenipal', 'unidad'),
('RM-070', 'Roca Fosforica', 'unidad'),
('RM-071', 'rukam', 'unidad'),
('RM-072', 'Sich', 'unidad'),
('RM-073', 'Sijo', 'unidad'),
('RM-074', 'Silicato de Potasio', 'unidad'),
('RM-075', 'Silicato de Sodio 32', 'unidad'),
('RM-076', 'Sorbitol 70%', 'unidad'),
('RM-077', 'Sulfato de Amonio', 'unidad'),
('RM-078', 'Sulfato de Cobre 5-HID', 'unidad'),
('RM-079', 'Sulfato de Magnesio 7-HID', 'unidad'),
('RM-080', 'Sulfato de Magnesio An', 'unidad'),
('RM-081', 'Sulfato de manganeso 7-HID', 'unidad'),
('RM-082', 'Sulfato de manganeso An', 'unidad'),
('RM-083', 'Sulfato de Potasio', 'unidad'),
('RM-084', 'Sulfato de Zinc 7-HID', 'unidad'),
('RM-085', 'Sulfato de Zinc An', 'unidad'),
('RM-086', 'Sulfato Ferroso 7-HID', 'unidad'),
('RM-087', 'Sulfato Ferroso Anhidro', 'unidad'),
('RM-088', 'Urea', 'unidad'),
('RM-089', 'vitamina B1', 'unidad'),
('RM-090', 'vitamina B2', 'unidad'),
('RM-091', 'vitamina B6', 'unidad'),
('RM-092', 'vitamina C', 'unidad'),
('RM-093', 'Vixil I (lignosulfonato de Na)', 'unidad'),
('RM-094', 'Vixileex SD', 'unidad'),
('RM-095', 'Tripolifosfato de Sodio', 'unidad'),
('RM-096', 'Antiespumante', 'unidad'),
('RM-097', 'Baricryl', 'unidad'),
('RM-098', 'Dioxido de Titanio', 'unidad'),
('RM-099', 'Carbonato de Calcio', 'unidad'),
('RM-100', 'Colanyl azul', 'unidad'),
('RM-101', 'Movilith DM-350', 'unidad'),
('RM-102', 'Texanol', 'unidad'),
('RM-103', 'Dietilenglicol', 'unidad'),
('RM-104', 'Acticide SPX (Isotiazolinonas)', 'unidad')
ON CONFLICT (code) DO NOTHING;
